//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int admin_ID { get; set; }
        public int staff_ID { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public bool superAdmin { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
