//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int donor_ID { get; set; }
        public string donorName { get; set; }
        public string donorLevel { get; set; }
        public string donorYear { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public bool active { get; set; }
    }
}
