//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int error_ID { get; set; }
        public string errorDesc { get; set; }
        public System.DateTime errorDate { get; set; }
        public Nullable<int> admin_ID { get; set; }
    }
}
