//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int event_ID { get; set; }
        public string eventName { get; set; }
        public System.DateTime eventDate { get; set; }
        public string eventTime { get; set; }
        public string eventLocation { get; set; }
        public string eventDetails { get; set; }
        public bool active { get; set; }
    }
}
