//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public int page_ID { get; set; }
        public string pageName { get; set; }
        public string pageDesc { get; set; }
        public string content { get; set; }
    }
}
