//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paradise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Story
    {
        public int story_ID { get; set; }
        public string storyTitle { get; set; }
        public string storyName { get; set; }
        public string storyContent { get; set; }
        public bool active { get; set; }
    }
}
